apiVersion: v1
data:
  osServiceAccount.json: <path:projects/{{ .Values.projectID }}/secrets/gcp-creds-secret#gcp-creds-secret#latest | base64encode>
kind: Secret
metadata:
  name: second-gcp-creds
  namespace: second
