apiVersion: v1
data:
  .dockerconfigjson: <path:projects/{{ .Values.projectID }}/secrets/pull-secret#pull-secret#latest | base64encode>
kind: Secret
metadata:
  name: second-pull-secret
  namespace: second
type: kubernetes.io/dockerconfigjson
