apiVersion: v1
stringData:
  install-config.yaml: |
    apiVersion: v1
    metadata:
      name: second
    baseDomain: {{ .Values.baseDomain }} 
    controlPlane:
      architecture: amd64
      hyperthreading: Enabled
      name: master
      replicas: 3
      platform:
        gcp:
          type: n1-standard-4
    compute:
    - hyperthreading: Enabled
      architecture: amd64
      name: 'worker'
      replicas: 3
      platform:
        gcp:
          type: n1-standard-4
    networking:
      networkType: OpenShiftSDN
      clusterNetwork:
      - cidr: 10.128.0.0/14
        hostPrefix: 23
      machineNetwork:
      - cidr: 10.0.0.0/16
      serviceNetwork:
      - 172.30.0.0/16
    platform:
      gcp:
        projectID: <path:projects/{{ .Values.projectID }}/secrets/project-id#project-id#latest>
        region: us-east1
    pullSecret: "" # skip, hive will inject based on it's secrets
    sshKey: "<path:projects/{{ .Values.projectID }}/secrets/ssh-public-key#ssh-public-key#latest>"
kind: Secret
metadata:
  name: second-install-config
  namespace: second
