apiVersion: v1
data:
  ssh-privatekey: <path:projects/{{ .Values.projectID }}/secrets/ssh-private-key#ssh-private-key#latest | base64encode>
kind: Secret
metadata:
  name: second-ssh-private-key
  namespace: second
